global:
  scrape_interval: 5s  # 5초마다 메트릭 수집

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # 로컬에서 실행 중인 Spring Boot API

  - job_name: 'kafka-broker'
    metrics_path: '/'
    static_configs:
      - targets: ['localhost:7071']  # JMX Exporter가 실행 중인 포트
